version: '3.8'

services:
  # PostgreSQL만 (가장 필수적인 것)
  postgres:
    image: postgres:15-alpine  # 더 가벼운 alpine 버전
    container_name: ai-dbagent-postgres-dev
    environment:
      POSTGRES_DB: dbagent
      POSTGRES_USER: dbagentuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    # 헬스체크 제거로 시작 시간 단축
    restart: unless-stopped

volumes:
  postgres_dev_data: